# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8800003550e77f6efcd11430c255cce28e9208783c86ce929ff402c758f03748de86735a3a2febcab140bae173251ba16d6ff499b6c3533fe143f51ba427655b

test:
  secret_key_base: 74ac72d36470393873117e13acbd480ae9cc32eaa926c2a48ab7119b03c62bdf15af4c8396ef016be01fbf4e681f38ab84451829028423e0b6ce1834d13f6673

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
